image:
  registry: registry.k8s.io
  repository: external-dns/external-dns
  tag: v0.14.0

provider: webhook

extraArgs:
  webhook-provider-url: http://localhost:8888
  txt-prefix: reg-

sidecars:
- name: hetzner-webhook
  image: ghcr.io/mconfalonieri/external-dns-hetzner-webhook:v0.6.0
  ports:
  - containerPort: 8888
    name: webhook
  - containerPort: 8080
    name: http
  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 10
    timeoutSeconds: 5
  readinessProbe:
    httpGet:
      path: /ready
      port: http
    initialDelaySeconds: 10
    timeoutSeconds: 5
  env:
  - name: HETZNER_API_KEY
    valueFrom:
      secretKeyRef:
        name: hetzner-credentials-external-dns
        key: api-key
